[phases.setup]
nixPkgs = ["nodejs_22", "python3", "gcc", "gnumake", "pkg-config", "systemd"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server/dist/index.js"
